[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
tracing = "0.1.41"
tokio = "1.47.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
